cadena = input("Introduzca una cadena con espacios en blanco al principio y al final:")
print("Longitud de la cadena:", len(cadena))
cadenalstrip = cadena.lstrip()
print("Cadena (lstrip):",cadenalstrip,end='.')
print("\nLongitud de la cadena (lstrip):", len(cadenalstrip))
cadenarstrip = cadena.rstrip()
print("Cadena (rstrip):",cadenarstrip,end='.')
print("\nLongitud de la cadena (rstrip):", len(cadenarstrip))
cadenastrip = cadena.strip()
print("Cadena (strip):",cadenastrip,end='.')
print("\nLongitud de la cadena (strip):", len(cadenastrip))
