cadena = input("Introduzca una cadena:")
reemplazar = input("Introduzca una subcadena de la anterior para reemplazar:")
reemplazo = input("Introduzca la cadena por la que se reemplazará la anterior:")
print("Cadena original:", cadena)
print("Cadena nueva (replace):", cadena.replace(reemplazar, reemplazo))
