import math
print("El valor absoluto de -123 es: ", math.fabs(-123))
print("El factorial de 7 es: ", math.factorial(7))
print("El máximo común divisor de 9 y 15 es: ", math.gcd(9,15))
print("isnan(3): ",math.isnan(3))
print("El logaritmo en base 10 de 100 es: ", math.log(89,10))
print("El valor de 3 elevado a 4 es: ", math.pow(3,4))
print("La raiz cuadrada de 49 es: ", math.sqrt(49))
print("El ángulo 90 en radianes es: ", math.radians(90))
print("El ángulo 1.23 en grados es: ", math.degrees(1.23))
print("El seno de un ángulo de 90 es: ", math.sin(math.radians(90)))
print("El coseno de un ángulo de 90 es: ", math.cos(math.radians(90)))
print("La tangente de un ángulo de 90 es: ", math.tan(math.radians(90)))
print("El arcoseno de 1 es: ", math.degrees(math.asin(1)))
print("El arcocoseno de 1 es: ", math.degrees(math.acos(1)))
print("La arcotangente de 1 es: ", math.degrees(math.atan(1)))

print("El valor de pi es: ", math.pi)
print("El valor de e es: ", math.e)
print("El valor de tau es: ", math.tau)
print("El valor infinito es: ", math.inf)
print("El valor NaN es: ", math.nan)
