print("FICHERO INICIAL")
flectura = open("fichero_escritura.txt","r")
texto = flectura.read()
flectura.close()
print(texto)
print("INSERTANDO LÍNEA...\n")
fescritura = open("fichero_escritura.txt","a")
fescritura.seek(0)
fescritura.close()
fescritura.writelines(["Nueva linea en el fichero2\n","nueva linea"])
fescritura.close()
print("FICHERO INICIAL")
flectura = open("fichero_escritura.txt","r")
texto = flectura.read()
flectura.close()
print(texto)
