print("FICHERO INICIAL")
flectura = open("fichero.txt","r")
texto = flectura.read()
flectura.close()
print(texto)
print("INSERTANDO LÍNEA...\n")
fescritura = open("fichero.txt","a")
fescritura.write("Nueva linea en el fichero\n")
fescritura.close()
print("FICHERO INICIAL")
flectura = open("fichero.txt","r")
texto = flectura.read()
flectura.close()
print(texto)
